--SUBPROGRAME 
SET SERVEROUTPUT ON;
--Procedura modifica_salariul primeşte doi parametrii: p_id_angajat şi procent şi majorează cu procentul specificat salariul angajatului cu id_angajat=p_id_angajat:
CREATE OR REPLACE PROCEDURE 
MODIFICA_SAL_PROCENT(P_ID_ANGAJAT IN ANGAJATI.ID_ANGAJAT%TYPE, PROCENT IN NUMBER)
IS
V_SALARIUL ANGAJATI.SALARIUL%TYPE;
BEGIN
SELECT SALARIUL INTO V_SALARIUL FROM ANGAJATI WHERE ID_ANGAJAT= P_ID_ANGAJAT;
DBMS_OUTPUT.PUT_LINE('ANGAJATUL ARE SALARIUL '|| V_SALARIUL);
UPDATE ANGAJATI SET SALARIUL = SALARIUL * (PROCENT/100 + 1)  WHERE ID_ANGAJAT = P_ID_ANGAJAT;
SELECT SALARIUL INTO V_SALARIUL FROM ANGAJATI WHERE ID_ANGAJAT= P_ID_ANGAJAT;
DBMS_OUTPUT.PUT_LINE('ANGAJATUL ARE SALARIUL '|| V_SALARIUL);
END;
/
SHOW ERRORS;
CALL MODIFICA_SAL_PROCENT(176,10);
EXECUTE MODIFICA_SAL_PROCENT(176,10);
BEGIN
MODIFICA_SAL_PROCENT(176,10);
END;
/

--Procedura primeşte ca parametru de tip IN id_ul unui angajat şi returnează prin parametrii de tip OUT numele şi salariul acestuia:
CREATE OR REPLACE PROCEDURE ANGAJAT (P_ID_ANGAJAT IN ANGAJATI.ID_ANGAJAT%TYPE, P_NUME OUT ANGAJATI.NUME%TYPE,
P_SALARIUL OUT ANGAJATI.SALARIUL%TYPE)
IS
BEGIN
SELECT NUME, SALARIUL INTO P_NUME, P_SALARIUL FROM ANGAJATI WHERE ID_ANGAJAT = P_ID_ANGAJAT;
DBMS_OUTPUT.PUT_LINE('ANGAJATUL '|| P_NUME||' ARE SAALRIUL '|| P_SALARIUL);
END;
/

DECLARE 
NUME ANGAJATI.NUME%TYPE;
SALARIUL ANGAJATI.SALARIUL%TYPE;
BEGIN
ANGAJAT(176, NUME, SALARIUL);
END;
/

--Procedura calculează salariul mediu şi îl returnează printr-un parametru de tip OUT:
CREATE OR REPLACE PROCEDURE SAL_MEDIU (P_MEDIU OUT NUMBER)
IS
BEGIN
SELECT AVG(SALARIUL) INTO P_MEDIU FROM ANGAJATI;
END;
/

VARIABLE G_SAL_MEDIU NUMBER;
EXECUTE SAL_MEDIU(:G_SAL_MEDIU);
PRINT G_SAL_MEDIU;


--Procedura modifică salariul unui angajat doar în cazul în care este mai mic decât media prin apelarea procedurii create mai sus, MODIFICA_SALARIUL_PROCENT. Procedura primeşte id-ul angajatului ca parametru de intrare şi salariul mediu actual şi prin returnează prin parametrul de tip IN OUT salariul mediu modificat prin apelul procedurii SAL_MEDIU.
CREATE OR REPLACE PROCEDURE MODIFICARE (P_ID_ANGAJAT IN ANGAJATI.ID_ANGAJAT%TYPE, P_PROCENT IN NUMBER)
IS
V_MEDIU NUMBER;
V_SALARIUL ANGAJATI.SALARIUL%TYPE;
V_NUME ANGAJATI.NUME%TYPE;
BEGIN
ANGAJAT(P_ID_ANGAJAT, V_NUME, V_SALARIUL);
SAL_MEDIU (V_MEDIU);
SELECT SALARIUL INTO V_SALARIUL FROM ANGAJATI WHERE ID_ANGAJAT = P_ID_ANGAJAT;
IF V_SALARIUL < V_MEDIU THEN MODIFICA_SAL_PROCENT(P_ID_ANGAJAT, P_PROCENT);
END IF;
ANGAJAT(P_ID_ANGAJAT, V_NUME, V_SALARIUL);
END;
/
DECLARE
MEDIU NUMBER;
BEGIN
SAL_MEDIU(MEDIU);
DBMS_OUTPUT.PUT_LINE (ROUND(MEDIU, 2));
MODIFICARE(105, 10);
SAL_MEDIU(MEDIU);
DBMS_OUTPUT.PUT_LINE (ROUND(MEDIU, 2));
END;
/

DROP PROCEDURE MODIFICARE;
ROLLBACK;
SELECT OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PROCEDURE';
SELECT TEXT FROM USER_SOURCE WHERE NAME ='ANGAJAT' AND TYPE = 'PROCEDURE';

--FUNCTII

--Funcția  verifica_salariul returnează TRUE/FALSE daca salariatul are salariul mai mare/mai mic sau egal cu salariul mediu  si NULL daca salariatul nu exista
CREATE OR REPLACE FUNCTION VERIFICA_SAL ( P_ID_ANGAJAT IN ANGAJATI.ID_ANGAJAT%TYPE, P_MEDIU IN NUMBER) RETURN BOOLEAN
IS
V_SAL ANGAJATI.SALARIUL%TYPE;
BEGIN
SELECT SALARIUL INTO V_SAL FROM ANGAJATI WHERE ID_ANGAJAT = P_ID_ANGAJAT;
IF V_SAL < P_MEDIU THEN RETURN FALSE;
ELSE RETURN TRUE;
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('NU EXISTA ANGAAJTUL');
WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('A APARUT O EROARE');
END;
/

DECLARE 
MEDIU NUMBER;
REZ BOOLEAN;
BEGIN
SAL_MEDIU(MEDIU);
DBMS_OUTPUT.PUT_LINE(ROUND(MEDIU, 3));
REZ := VERIFICA_SAL(176, MEDIU);
IF REZ = TRUE THEN DBMS_OUTPUT.PUT_LINE('ARE SAL MAI MARE');
ELSE
DBMS_OUTPUT.PUT_LINE('ARE SAL MAI MIC');
END IF;
END;
/

DESCRIBE VERIFICA_SAL;   

CREATE OR REPLACE FUNCTION TAXA (value IN NUMBER, proc IN NUMBER)
RETURN NUMBER IS
BEGIN
RETURN (value*proc/100);
END taxa;
/

SELECT TAXA(100,20) FROM DUAL;

--Apelul urmatoarei functii dintr-o instructiune SQL va returna o eroare: ORA-04091: table [nume_tabela] is mutating, trigger/function may not see it
CREATE OR REPLACE FUNCTION produs_nou (pret_min in NUMBER) 
RETURN NUMBER 
IS
BEGIN
INSERT INTO produse values (1, 'cafea', 'kg','categorie',100, pret_min);
RETURN (pret_min+100);
END;
/

UPDATE produse 
SET pret_min= produs_nou(2000)
WHERE id_produs=111;

